name: release
on:
  push:
    # tags: # 当我们提交代码为tag 是以'v'开头的时候才会触发自动部署到服务端 如 git push tag v0.1.0
    #   - 'v*'
    branches:
      - main
jobs:
  buildWindow:
    runs-on: windows-latest
    steps:
      # 下载源码
      - name: Checkout Code
        id: CheckoutCode
        uses: actions/checkout@v2

      # 打包构建 Server
      - name: Setup Go
        id: SetupGo
        uses: actions/setup-go@v2
        with:
          go-version: "1.19.13"
      - name: Setup GCC
        id: setupGCC
        uses: rlalik/setup-cpp-compiler@v1.2
        with:
          compiler: gcc-10.2.0

      - run: go version
      - run: gcc --version
      - run: C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin\gcc.exe --version

  buildLinux:
    runs-on: ubuntu-latest
    steps:
      # 下载源码
      - name: Checkout Code
        id: CheckoutCode
        uses: actions/checkout@v2

      # 打包构建 Server
      - name: Setup Go
        id: SetupGo
        uses: actions/setup-go@v2
        with:
          go-version: "1.19.13"

      - run: go version
      - run: gcc --version

  buildMAC:
    runs-on: macos-latest
    steps:
      # 下载源码
      - name: Checkout Code
        id: CheckoutCode
        uses: actions/checkout@v2

      # 打包构建 Server
      - name: Setup Go
        id: SetupGo
        uses: actions/setup-go@v2
        with:
          go-version: "1.19.13"

      - run: go version
      - run: gcc --version
